# Generated by Django 3.2.5 on 2021-11-26 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('parceiros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_evento', models.CharField(help_text='Insira o nome do evento.', max_length=100, unique=True, verbose_name='Nome do Evento')),
                ('descricao_evento', models.TextField(help_text='Faça uma breve descrição sobre o evento.', unique=True, verbose_name='Descrição do Evento')),
                ('local_evento', models.CharField(help_text='Exemplo: Rua, número, Bairro, CEP, Município, UF', max_length=150, verbose_name='Local do Evento')),
                ('data_evento', models.DateTimeField(help_text='Data de realização do evento.', verbose_name='Data do Evento')),
                ('parceiros', models.ManyToManyField(help_text='Insira os parceiros do evento.', to='parceiros.Parceiros', verbose_name='Parceiros')),
            ],
        ),
    ]
