# Generated by Django 3.2.6 on 2021-09-21 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parceiros', '0001_initial'),
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='parceiros',
            field=models.ManyToManyField(help_text='Insira os parceiros do evento.', to='parceiros.Parceiros', verbose_name='Parceiros'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='data_evento',
            field=models.DateTimeField(help_text='Data de realização do evento.', verbose_name='Data do Evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='descricao_evento',
            field=models.TextField(help_text='Faça uma breve descrição sobre o evento.', unique=True, verbose_name='Descrição do Evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='local_evento',
            field=models.CharField(help_text='Exemplo: Rua, número, Bairro, CEP, Município, UF', max_length=150, verbose_name='Local do Evento'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='nome_evento',
            field=models.CharField(help_text='Insira o nome do evento.', max_length=100, unique=True, verbose_name='Nome do Evento'),
        ),
    ]
