# Generated by Django 3.2.5 on 2021-11-20 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0002_auto_20210920_2238'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['-data_evento', 'nome_evento']},
        ),
    ]
