# Generated by Django 3.2.5 on 2021-11-26 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0003_alter_evento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['data_evento', 'nome_evento']},
        ),
    ]
