# Generated by Django 3.2.5 on 2021-11-26 15:42

from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EspecieAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especie', models.CharField(help_text='Escreve a espécie do animal.', max_length=50, unique=True, verbose_name='Espécie')),
            ],
            options={
                'db_table': 'especie',
                'ordering': ['especie'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docfile', models.FileField(upload_to='cadastro/media/%Y_%m_%d')),
                ('nome_cachorro', models.CharField(help_text='Insira o nome do animal.', max_length=30, verbose_name='Nome')),
                ('descricao', djrichtextfield.models.RichTextField(default='')),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], help_text='Escolha o sexo do animal.', max_length=1, null=True, verbose_name='Sexo')),
                ('tipo', models.CharField(choices=[('D', 'Doméstico'), ('S', 'Selvagem')], help_text='Escolha o tipo do animal.', max_length=1, null=True, verbose_name='Tipo')),
                ('porte', models.CharField(choices=[('P', 'Pequeno'), ('M', 'Médio'), ('G', 'Grande')], help_text='Escolha o porte do animal.', max_length=1, null=True, verbose_name='Porte')),
                ('data_nascimento', models.DateTimeField(help_text='Coloque a data aproximada de nascimento do animal.', null=True, verbose_name='Nascimento')),
                ('url', models.URLField(null=True)),
                ('especie', models.ForeignKey(blank=True, default=2, null=True, on_delete=django.db.models.deletion.CASCADE, to='cadastro.especieanimal')),
            ],
            options={
                'db_table': 'mural_fofura',
                'ordering': ['nome_cachorro', 'data_nascimento', 'tipo', 'porte'],
            },
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro.question')),
            ],
        ),
    ]
