# Generated by Django 3.2.6 on 2021-11-20 15:10

from django.db import migrations
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='descricao',
            field=djrichtextfield.models.RichTextField(default=''),
        ),
    ]
