# Generated by Django 3.2.5 on 2021-11-27 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={},
        ),
        migrations.AlterModelOptions(
            name='especieanimal',
            options={},
        ),
        migrations.AlterModelTable(
            name='document',
            table=None,
        ),
        migrations.AlterModelTable(
            name='especieanimal',
            table=None,
        ),
    ]
