# Generated by Django 3.2.6 on 2021-11-20 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0003_auto_20211120_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='especie_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='cadastro.especieanimal'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='url',
            field=models.URLField(null=True),
        ),
    ]
