# Generated by Django 3.2.6 on 2021-11-21 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0004_auto_20211120_1350'),
        ('cadastro', '0004_auto_20211120_1716'),
    ]

    operations = [
    ]
