# Generated by Django 3.2.6 on 2021-11-25 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0005_merge_0004_auto_20211120_1350_0004_auto_20211120_1716'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['nome_cachorro', 'data_nascimento', 'tipo', 'porte']},
        ),
        migrations.AlterModelOptions(
            name='especieanimal',
            options={'ordering': ['especie']},
        ),
        migrations.RemoveField(
            model_name='document',
            name='especie_id',
        ),
        migrations.RemoveField(
            model_name='document',
            name='idade_cachorro',
        ),
        migrations.RemoveField(
            model_name='document',
            name='porte_cachorro',
        ),
        migrations.AlterField(
            model_name='document',
            name='nome_cachorro',
            field=models.CharField(help_text='Insira o nome do animal.', max_length=30, verbose_name='Nome'),
        ),
        migrations.AlterModelTable(
            name='document',
            table='mural_fofura',
        ),
        migrations.AlterModelTable(
            name='especieanimal',
            table='especie',
        ),
    ]
