# Generated by Django 3.2.5 on 2021-11-26 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0006_auto_20211125_0906'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='url',
        ),
    ]
