# Generated by Django 3.2.5 on 2021-11-26 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0007_remove_document_url'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='document',
            table='mural_fofura_',
        ),
    ]
