# Generated by Django 3.2.5 on 2021-11-26 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro', '0008_alter_document_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='document',
            table='mural_fofura',
        ),
    ]
