# Generated by Django 3.2.5 on 2021-11-26 16:57

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parceiros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_parceiro', models.CharField(help_text='Escreve o nome do Parceiro.', max_length=100, unique=True, verbose_name='Parceiro')),
                ('descricao_parceiro', djrichtextfield.models.RichTextField(default='')),
                ('site_parceiro', models.URLField(help_text='Insira o site do parceiro.', null=True, verbose_name='Site')),
            ],
        ),
    ]
