# Generated by Django 3.2.5 on 2021-11-20 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parceiros', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='parceiros',
            options={'ordering': ['nome_parceiro']},
        ),
    ]
