# Generated by Django 3.2.6 on 2021-11-23 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parceiros', '0002_alter_parceiros_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceiros',
            name='site_parceiro',
            field=models.URLField(null=True),
        ),
    ]
