# Generated by Django 3.2.6 on 2021-11-23 22:36

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    dependencies = [
        ('parceiros', '0003_alter_parceiros_site_parceiro'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parceiros',
            name='descricao_parceiro',
            field=djrichtextfield.models.RichTextField(default=''),
        ),
        migrations.AlterField(
            model_name='parceiros',
            name='site_parceiro',
            field=models.URLField(help_text='Insira o site do parceiro.', null=True, verbose_name='Site'),
        ),
    ]
